# Generated by Django 3.0.5 on 2020-05-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=300)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('WORKING', '進行中'), ('完了', 'DONE')], default='WAITING', max_length=7)),
            ],
        ),
    ]
